### ISSUE TITLE
Incorrect work of code if there are no spaces which not related to the logic of the code

### ISSUE THREAD

**Issue by OKhalkov** [thingsboard/tbel#2]
**Invalid code of converter (TBEL):**
```javascript
var deviceName= 'Device A';
var deviceType= 'thermostat';
var result= {
   deviceName: deviceName,
   deviceType: deviceType
};

return result;
```
Spaces were deliberately **missed** between the **equals sign** and the **variable name**, therefore occur error
![image](https://user-images.githubusercontent.com/85943596/206714118-c9280bf2-cc52-405c-bb13-e4fd9a4a896f.png)

**The same code that works:**
```javascript
var deviceName = 'Device A';
var deviceType = 'thermostat';
var result = {
   deviceName: deviceName,
   deviceType: deviceType
};

return result;
```

**Comment by ikulikov** [comment]
Fixed in version 1.0.4. Commit 2b6084b.
